config/routes.rb
Plotomeu::Application.routes.draw do
  devise_for :users

  resources :teachers
  resources :students

  resources :thermal_capacities 
  resources :thermal_capacities_materials
  resources :thermal_capacities_temp
  resources :thermo_filter do
    member do
      get "filter"
    end
  end

  resources :pendulum_length
  resources :pendulum_mass
  resources :pendulum_angle
  resources :pendulum_filter do
    member do 
      get "filter"
    end
  end

  resources :static_pages do
    collection do
      get "set_name"
      get "filter"
    end
  end
  resources :data_points do
    collection do
      get "updateGraph"
    end
  end

  resources :answers do
    collection do
      post "leave_page"
    end
  end

  resources :templates 

  resources :activities do
    member do
      get "updateTeacherGraph"
      get "switch"
    end
  end

  resources :statues do
    collection do
      post "add_prediction"
    end
  end

  root to: "static_pages#index"

end

app/controllers/static_pages_controller.rb
# -*- coding: utf-8 -*-
class StaticPagesController < ApplicationController
  def index
    if params[:code]
      t = Template.find(params[:template_id])
      a = t.activities.where(code: params[:code]).first
      
      if a
        session[:deadline] = a.deadline
        session[:template] = t.id
        session[:activity] = a.id
        session[:url] = t.url
        
        if signed_in? && current_user.role == "student"
          remove_anonymous_data_points
          session[:student] = current_user.id
          answer = Answer.new(answers: [""], questions: [""])
          answer.activity_id = a.id
          answer.user_id = current_user.id
          answer.submited = false
          answer.save
          session[:answer] = answer.id
          session[:prediction] = nil
          
        end
        
        redirect_to t.url
      else
        flash[:alert] = "Não existe nada com esse código"
        redirect_to root_path
      end
    else
      show_home_page(params)
      
    end
    
  end



  def set_name
    
    unless session[:activity]
      redirect_to root_path
    else
      remove_anonymous_data_points
      session[:prediction] = nil
      
    end

    create_user(params)
    
    respond_to do |format|
        format.html
        format.js
    end
  end 

  


  def filter
    answer = Answer.find(session[:answer])
    answer.activity_id = params[:activity]
    answer.save
    session[:activity] = params[:activity]
    session[:url] = params[:url]
    session[:template] = params[:template]
    redirect_to params[:url]
  end






  private
  def remove_anonymous_data_points
    activity = Activity.find(session[:activity])
    answers = activity.answers.old
    
    answers.each do |i|
      i.destroy
    end
    
  end


  def create_user(params)
    pass = rand(36**7...(36**8)).to_s(36)
    s = User.new(email: nil, password: pass, name: params[:name], role: "student", account_type: 2)
    if s.save
      session[:student] = s.id
      answer = Answer.new(answers: [""], questions: [""], parameters:[""])
      answer.activity_id = session[:activity]
      answer.user_id = s.id
      answer.submited = false
      answer.save
      session[:answer] = answer.id
      
      cap = []
      s.name.split.each do |n|
        cap << n.capitalize
      end
      s.name = cap.join(" ")
      s.save
     
    else
      flash[:alert] = "Por favor introduza o nome"
      
    end
  end 


  def show_home_page(params)
    cat = params[:category] || 1
    @subcategories = SubCategory.all
    t = Template.where(sub_category_id: cat, filter_id: nil)

    @templates = []
    tmp = []
    
    t.each do |e|
      
      tmp << e
      if tmp.count == 2
        @templates << tmp
        tmp = []
      end
    end
    @templates << tmp if tmp.count == 1
          

    respond_to do |format|
      format.html
      format.js {render :index, :locals => {:cat => cat}}
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_templates.html.erb
<% @templates.each_with_index do |s,i| %>
<% if s.count == 2 %>
<div class="template_pair_index">
  <div class="template_cell_index template_cell_left_index" data-url=<%= s[0].id %>>
    <div class="template_title_index"><%= s[0].title %></div>
    <div class="template_image_description_index" data-number=<%= i*2+1 %>>
      <div class="template_image_index"><%= image_tag(s[0].img, size:"280x154", draggable: false) %> </div>
      <div class="template_description_index"><%= t s[0].description %></div>
    </div>
  </div>
  

  <div class="template_cell_index template_cell_right_index" data-url=<%= s[1].id %>>
    <div class="template_title_index"><%= s[1].title %></div>
    <div class="template_image_description_index"  data-number=<%= i*2+2 %>>
      <div class="template_image_index"><%= image_tag(s[1].img, size:"280x154", draggable: false) %> </div>
      <div class="template_description_index"><%= t s[1].description %></div>
    </div>
  </div>

</div>

<% else %>
<div class="template_pair_index">
  <div class="template_cell_index template_cell_left_index" data-url=<%= s[0].id %>>
    <div class="template_title_index"><%= s[0].title %></div>
    <div class="template_image_description_index"  data-number=<%= i*2+1 %>>
      <div class="template_image_index"><%= image_tag(s[0].img, size:"280x154", draggable: false) %> </div>
      <div class="template_description_index"><%= t s[0].description %></div>
    </div>
  </div>
</div>

<% end %>
<% end %>

app/views/static_pages/index.html.erb
<%= render "layouts/navbar" %>


<section class="row" style="margin-top:60px;">

<section class="span3" id="template_navbar">

  <div id="template_general_navbar">
    <% @subcategories.each do |s| %>
    <% if s.id == 1 %>
    <p id="category_<%= s.id %>" class="template_selected template_category"><%= link_to I18n.translate(s.title), static_pages_path(category: s.id), remote:true %></p>
    <% else %>
    <p id="category_<%= s.id %>" class="template_category"><%= link_to t(s.title), static_pages_path(category: s.id), remote:true %></p>
    <% end %>
    <% end %>
  </div>
  <div id="template_specific_navbar">
    <%= link_to "voltar", remote:true %>
  </div>
</section>

<section class="span9" id="template_index">
  <%= render "templates" %>

</section>



</section>

app/views/static_pages/index.js.erb
$(".alert").remove();

$('#template_index').html("<%= escape_javascript(render(:partial => 'templates')) %>");

$(".template_selected").removeClass("template_selected");

$("#category_<%= cat %>").addClass("template_selected");

app/views/static_pages/set_name.js.erb
<% if flash[:alert] %>
   $("#alert").val("<%= flash[:alert] %>");
   window.location.replace("<%= session[:url] %>")
<% else %>
   $("#alert").hide();
   $(".name_getter").slideUp();
   $(".background").slideDown();
<% end %>