config/routes.rb
Plotomeu::Application.routes.draw do
  devise_for :users

  resources :teachers
  resources :students

  resources :thermal_capacities 
  resources :thermal_capacities_materials
  resources :thermal_capacities_temp
  resources :thermo_filter do
    member do
      get "filter"
    end
  end

  resources :pendulum_length
  resources :pendulum_mass
  resources :pendulum_angle
  resources :pendulum_filter do
    member do 
      get "filter"
    end
  end

  resources :static_pages do
    collection do
      get "set_name"
      get "filter"
    end
  end
  resources :data_points do
    collection do
      get "updateGraph"
    end
  end

  resources :answers do
    collection do
      post "leave_page"
    end
  end

  resources :templates 

  resources :activities do
    member do
      get "updateTeacherGraph"
      get "switch"
    end
  end

  resources :statues do
    collection do
      post "add_prediction"
    end
  end

  root to: "static_pages#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :code, :deadline,  :description
  
  validates :code, presence: true, uniqueness: {scope: :template_id}, length: {minimum: 3}
  validates :template_id, presence: true
  validates :user_id, presence: true
  
  
  belongs_to :template
  has_many :data_points, dependent: :destroy
  has_many :answers, dependent: :destroy
  
  has_many :filtered, class_name: "Activity", foreign_key: "filter_id"
  belongs_to :filter, class_name: "Activity"


  def filter?
    self.filtered.count > 0 ? true : false
  end
end

app/models/answer.rb
# -*- coding: utf-8 -*-

class Answer < ActiveRecord::Base
  attr_accessible  :answers, :questions,  :time_submission, :submited, :parameters

  validates :activity_id, presence: true
  validates :user_id, presence: true
  validates :answers, presence: true
  validates :questions, presence: true
  validates :parameters, presence: true
  validate :answers_length

  serialize :answers
  serialize :questions
  serialize :parameters

  belongs_to :user
  has_many :data_points, dependent: :destroy
  
  def answers_length
    if answers && questions 
      if answers.length != questions.length
        errors.add(:answers, "o número de respostas não é igual ao número de perguntas")
      end
    end
  end

  scope :old, -> { where("created_at < ? and submited = ?", Time.now-18000, false)}
  scope :submited, -> { where("submited = ?", true) }

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title

  has_many :sub_categories, dependent: :destroy
end

app/models/data_point.rb
class DataPoint < ActiveRecord::Base
  attr_accessible :x, :y, :series

  validates :x, presence: true
  validates :y, presence: true
  validates :answer_id, presence: true
  validates :activity_id, presence: true

  belongs_to :answer
  belongs_to :activity
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  
  attr_accessible  :title

  belongs_to :category
end

app/models/template.rb
class Template < ActiveRecord::Base
  attr_accessible :url, :description, :title

  validates :url, presence: true, uniqueness: {case_sensitive: false}
  validates :description, presence: true
  validates :title, presence: true, uniqueness: {case_sensitive: false}


  has_many :activities, dependent: :destroy

  has_many :filtered, class_name: "Template", foreign_key: "filter_id"
  belongs_to :filter, class_name: "Template"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :login, :name, :role , :account_type
  # attr_accessible :title, :body

  
  validates :login, presence: true, uniqueness: {case_sensitive: false}
  validates :role, presence: true
  validate :student_name
  
  has_many :activities
  has_many :data_points, through: :answers
  has_many :answers, dependent: :destroy
  serialize :completed

  before_validation :populate_fields

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def populate_fields
    x = rand(36**7...36**8).to_s(36)
    z = rand(36**7...36**8).to_s(36)
    if self.role == "1" || self.role == "student" then self.role = "student" else self.role = "teacher" end
    
    self.email = "#{z}noEmail#{x}@example.com" if !self.email || self.email == ""
    self.login = "#{z}noLogin#{x}" if self.account_type == 2
    self.completed ||= []
  end


  def student_name
    if self.role == "student"
      if !self.name || self.name == ""
        errors.add(:name, "no_name_error")
      end
    end
  end


  def get_activity_with_template(id)
    self.activities.includes(:template).where(id: id).first
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include AnswerCompilation

  before_filter :authenticate_user!, only: [:destroy]

  def create
    a = Answer.find(session[:answer])
    a.questions = []
    a.answers = []
    a.parameters = []

    a.questions << "modelo"
    a.answers << params[:model]
    
    a.questions << params[:question1]
    a.questions << params[:question2]
    a.questions << params[:question3]
    a.questions << params[:question4]
    
    a.answers << params[:answer1]
    a.answers << params[:answer2]
    a.answers << params[:answer3]
    a.answers << params[:answer4]

    a.parameters << params[:param_k]
    a.parameters << params[:param_h]
    a.parameters << params[:param_b]
    
    a.time_submission = Time.now
    
    a.submited = true
    a.save

    markAnswerCompleted(session[:activity]) if signed_in?
    
    session[:activity] = nil

    respond_to do |format| 
      format.js {render "#{session[:url]}/create_answers" }
    end
    
  end



  def destroy
    a = Answer.find(params[:id])
    @activity = current_user.activities.where(id: params[:activity_id]).first
    @answers = @activity.answers.includes(:data_points, :user).order("users.name")
    if @activity && a.activity_id == @activity.id
      u = User.find(a.user_id)
      u.completed.delete(@activity.template_id)
      u.save
      a.destroy
    else
      redirect_to root_path
    end

    compile_answers()
      

    respond_to do |format|
      format.js 
    end
  end

  
  def leave_page
    if (session[:answer])
      a = Answer.find(session[:answer])
      unless a.submited
        a.destroy
      end
    end

    respond_to do |format|
      format.js
    end
  end


  private
  def markAnswerCompleted(a)
    act = Activity.find(a)
    t = act.template_id
    current_user.completed << t unless current_user.completed.include? t
    current_user.save
  end
end

app/controllers/statues_controller.rb
class StatuesController < ApplicationController

  def index
    if session[:url] != request.path || session[:activity] == nil
      redirect_to root_path
    end
    
    @user = user_signed_in?
  end


  def add_prediction
    session[:prediction] = params[:mass]

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_points_helper.rb
module DataPointsHelper
end

app/helpers/pendulum_angle_helper.rb
module PendulumAngleHelper
end

app/helpers/pendulum_filter_helper.rb
module PendulumFilterHelper
end

app/helpers/pendulum_length_helper.rb
module PendulumLengthHelper
end

app/helpers/pendulum_mass_helper.rb
module PendulumMassHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statues_helper.rb
module StatuesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/thermo_filter_helper.rb
module ThermoFilterHelper
end

app/views/statues/create_data_points.js.erb
$('#statue_data_collection').html("");

$('#statue_data_collection').html("<%= escape_javascript(render(:partial => 'statues/tbody')) %>");


if (<%= @data.count != 0 %>) {
   <% if @data.count == 1 && @data.first.x != 0 %>
   
      $("#fancy_size").html(<%= @data.first.x %>);
      $("#fancy_mass").html(<%= @data.first.y %>);
      $("#fancy_trigger").click();
   <% elsif @data.count == 2 && @data.first.x == 0 %> 
      $("#fancy_size").html(<%= @data.last.x %>);
      $("#fancy_mass").html(<%= @data.last.y %>);
      $("#fancy_trigger").click();
   <% end %>
     

$("#statue_data_collection_explanation").html("<p><%= t 'statue.data4' %></p>");

$("#statue_data-gathering_next").show();
}
else {
     $("#statue_data_collection_explanation").html("<p><%= t 'statue.data1' %></p>");
     $("#statue_data_collection_explanation").append("<p><%= t 'statue.data2' %></p>");
     $("#statue_data_collection_explanation").append("<p><%= t 'statue.data3' %></p>");

$("#statue_data-gathering_next").hide();
}

$("#statue_mass_field").val("");
$("#statue_size_field").val("");

app/views/statues/index.html.erb
<div style="margin-top: -60px" >

<% if !@user %>
<section class="name_getter" style="width:500px; margin: 200px auto ;">
  
  <p><%= t "getName" %></p>
  <%= form_tag("/static_pages/set_name", remote:true, method: "get", class:"form-horizontal") do %>
  <%= text_field_tag(:name, nil, id:"student_name_field") %>
  <%= submit_tag(:ok, id:"student_name_submit", class:"btn btn-success") %>
  <% end %>
</section>
<% end %>


<section class="background <% if !@user %>hidden_section<% end %>">
  <% if session[:deadline] %>
  <div class="alert alert-info">
  <%= t "deadline.intro" %><%= session[:deadline].strftime("%d/%m") %><%= t "deadline.end" %>
  </div>
  <% end %>

<div id="statue_background_div">

<h1><%= t "statue.title" %></h1>
<p><%= t "statue.intro1" %></p> <br />
<p><%= t "statue.intro2" %> </p>

</div>
<div class="btn-group statue_navigator">
<a type="button" class="statue_button btn btn-primary background_next" id="statue_background_next"><%= t "next" %></a>
</div>
</section>



<section class="strategy">

<div id="statue_strategy_div">
  <h2><%= t("strategy").capitalize %></h2>
  <div>
  <p><%= t "statue.strategy1" %>
  </p>
  <br />
  <p>
  <%= t "statue.strategy2" %>
  </p>
  </div>

  </div>
   
  <div class="btn-group statue_navigator" style="margin-top: 10px">
    <a type="button" class="statue_button btn btn-primary strategy_previous" id="statue_strategy_previous"><%= t("previous") %></a>
    <a type="button" class="statue_button btn btn-primary strategy_next" id="statue_strategy_next"><%= t("next") %></a>
  </div>
</section>






<section class="data-gathering row">
  
<script type="text/javascript">
$(function() {
    
    $(window).on("beforeunload", function() {
	$.ajax("answers/leave_page", {
            method: "post",
            }
        );
    });

    var canvas = $("#myCanvas");
    var context = canvas.get(0).getContext("2d");
    var canvas_width = 400;
    var canvas_height = 500;
    
    var time = 0;
    var animation = false;

    var animation_parameters = {last: 0, current: 0, dt:0};
    var ratio = 0.5;
    var height = 0.5;
    var mass = 123;

    var scale = new Image();
    var statue = new Image();

    scale.src = "assets/scale.png";
    $(scale).load(function() {
        statue.src = "assets/statue.png";
	draw_scale();

    });

    
    $(statue).load(function() {
	draw_statue();
    });

    function draw_statue() {
	context.scale(ratio,ratio);
	context.drawImage(statue,canvas_width/ratio*0.5-statue.width/2,canvas_height/ratio*0.78-statue.height);
	context.scale(1/ratio,1/ratio);

	context.beginPath();
	context.moveTo(324,388);
	context.lineTo(336,388);
	context.moveTo(330,388);
	context.lineTo(330,388-statue.height*ratio);
	context.moveTo(324,388-statue.height*ratio);
	context.lineTo(336,388-statue.height*ratio);
	context.closePath();
	context.stroke();

	var h = height*100*ratio;
	context.fillText(h.toFixed(0)+" cm", 350, 365);
    }

    function draw_scale() {
	context.drawImage(scale,50,350);
	var m = mass*Math.pow(height*ratio/0.1, 3)*(1.02-Math.random()*0.04)
	context.fillText(m.toFixed(0)+" g", 150, 465);
    }


     $("#statue_size_controls").on("slide", "#statue_size_slider", function(evt, ui) {
	    ratio = ui.value/50.;
	    context.clearRect(0,0,400,500);
	    draw_scale();
	    draw_statue();
	
    });

    
 
    
});

</script>


<h1><%= t "collectData" %></h1>
        
    <div class="model_data_form statue_data_form span5">
      <%= form_tag(data_points_path, remote: true) do %>
         <table class="table">
	    <thead>
	      <tr><th><%= t("height") %>(m)</th><th><%= t("mass") %>(kg)<th></th></tr>
	      <tr>
		 <th>
		   <%= number_field_tag(:x, nil,  class:"statue_input", placeholder:"metro",step:0.0001, id:"statue_size_field", max:1, min:0) %>
		 </th>
		 <th>
		   <%= number_field_tag(:y, nil, class:"statue_input", placeholder:"quilograma",step:0.001,  id:"statue_mass_field", max: 20, min:0) %>
		 </th>
		 
		 <th>
		   <%= submit_tag(:submeter, value: t('submit'), class:"btn btn-success model_add_data_point_button", id:"statue_add_data_point_button", style:"margin-top:-37px") %>
		 </th>
	      </tr>
	    </thead>
	  
	  
	  
	    <tbody class="model_data_collection" id="statue_data_collection">
	      
	    <%= render "tbody" %>
	    </tbody>
	  
	  </table>
    	  
      <% end %>
      <div id="statue_data_collection_explanation">
      <p><%= t "statue.data1" %></p>
      <p><%= t "statue.data2" %></p>
      <p><%= t "statue.data3" %></p>
      
      </div>
    </div>

    
    
    <div class="statue_animation span7">
    <canvas id="myCanvas" width=400 height=500></canvas>
   
    
      <div id="statue_size_controls" style="width:150px;  float:right; margin-top:-120px">
	 <div id="statue_size_label"><%= t("height").capitalize %></div>
	 <div id="statue_size_slider"></div>
      </div>
    
    
    
    
    </div>
    

    <div class="btn-group statue_navigator">
    <a type="button" class="statue_button btn btn-primary data-gathering_previous" id="statue_data-gathering_previous"><%= t "previous" %></a>
    <a type="button" class="statue_button btn btn-primary data-gathering_next" id="statue_data-gathering_next"  style="display:none"><%= t "next" %></a>
    </div>


    <a href="#fancydiv" class="fancybox" id="fancy_trigger" style="display:none"></a>

    <div  style="display:none;">
      <div id="fancydiv">
      <p><%= t "statue.prediction1" %><span id="fancy_size">0.1</span><%= t "statue.prediction2" %><span id="fancy_mass">0.095</span><%= t "statue.prediction3" %><br /><%= t "statue.prediction6" %></p>
      <%= form_tag(add_prediction_statues_path, remote:true) do %>
      <div class="form-horizontal">
      <%= number_field_tag(:mass,"", step:0.001, placeholder: t("statue.prediction4")) %>
      <%= submit_tag(:submeter, value:t("submit"),  class:"btn btn-success") %>
      <%= link_to t("statue.prediction5"), "#", id:"fancy_close", style:"margin-left:30px;" %>
      </div>
      <% end %>
      </div>
    </div>
</section>






<section class="model-choice">
  <div class="x_axis_unit axis_unit">l</div>
  <div class="y_axis_unit axis_unit">m</div>
      
  <h1><%= t("chooseModel") %></h1>
  <div>
  <div class="model_choice_buttons statue_model_buttons">
    <div class="model_first_model_controls" id="statue_first_model_controls">
  <div class="btn-group">
    <a type="button" class="statue_button btn linear_model_button" id="statue_linear_button"><%= t("linear").capitalize %><br/> y = k x + b</a>
    <a type="button" class="statue_button btn quadratic_model_button" id="statue_quadratic_button"><%= t("quadratic").capitalize %><br /> y = k (x-h)<sup>2</sup> + b</a>
    <a type="button" class="statue_button btn cubic_model_button" id="statue_cubic_button"><%= t("cubic").capitalize %><br /> y = k (x-h)<sup>3</sup> + b</a>
  </div>
    
  <div class="model-choice_buttons_explanation" id="statue_buttons_explanation"><%= t "chooseModelInstructions" %></div>
  <div class="linear_function_controls model_function_controls" id="statue_linear_controls">
    
    <div class="model_choice_slider_parent"><div class="function_controls_label">k: <span class="model_linear_m" id="statue_linear_m">120</span></div><div class="model_slider_controls model_linear_m_slider" id="statue_linear_m_slider"></div></div>
    <div class="model_choice_slider_parent"><div class="function_controls_label">b: <span class="model_linear_b" id="statue_linear_b">0</span></div><div class="model_slider_controls model_linear_b_slider" id="statue_linear_b_slider"></div></div>

  </div>
  <div class="quadratic_function_controls model_function_controls" id="statue_quadratic_controls">
    <div class="model_choice_slider_parent"><div class="function_controls_label">k: <span class="model_quadratic_k" id="statue_quadratic_k">2.6</span></div><div class="model_slider_controls model_quadratic_k_slider" id="statue_quadratic_k_slider"></div></div>
    <div class="model_choice_slider_parent"><div class="function_controls_label">h: <span class="model_quadratic_h" id="statue_quadratic_h">0</span></div><div class="model_slider_controls model_quadratic_h_slider" id="statue_quadratic_h_slider"></div></div>
    <div class="model_choice_slider_parent"><div class="function_controls_label">b: <span class="model_quadratic_b" id="statue_quadratic_b">0</span></div><div class="model_slider_controls model_quadratic_b_slider" id="statue_quadratic_b_slider"></div></div>
  </div>

  <div class="cubic_function_controls model_function_controls" id="statue_cubic_controls">
    <div class="model_choice_slider_parent"><div class="function_controls_label">k: <span class="model_cubic_k" id="statue_cubic_k">0.04</span></div><div class="model_slider_controls  model_cubic_k_slider" id="statue_cubic_k_slider"></div></div>
    <div class="model_choice_slider_parent"><div class="function_controls_label">h: <span class="model_cubic_h" id="statue_cubic_h">0</span></div><div class="model_slider_controls model_cubic_h_slider" id="statue_cubic_h_slider"></div></div>
    <div class="model_choice_slider_parent"><div class="function_controls_label">b: <span class="model_cubic_b" id="statue_cubic_b">0</span></div><div class="model_slider_controls model_cubic_b_slider" id="statue_cubic_b_slider"></div></div>
  </div>
  
  <div class="model_choice_model_information_div">
    <div class="model_choice_model_formula_parent" id="statue_chosen_model_div">
      <span>
	 <%= t("model").capitalize %>
      </span>
      <div class="model_choice_model_formula" id="statue_chosen_model">
	 
      </div>
    </div>
    <div class="model_choice_model_confirm_button" id="statue_confirm_model_button_div">
      <a type="button" class="model_confirm_model_button statue_button btn btn-success" id="statue_confirm_model_button"><%= t "useModel" %></a>
    </div>
    </div>
  </div>
  </div>
  <div id="statue_graph_super_div">
  <div><%= t "statue.graphTitle" %></div>
  <div id="statue_graph_div">
    <div class="y_label_div" id="statue_y_label">m (kg)</div>
    
  <div class="graph_div" id="statue_graph"></div>
  <div class="x_label_div" id="statue_x_label">l (m)</div>
  </div>
  <div class="graph_legend_container"></div>
   </div>
  </div>
  <div class="btn-group statue_navigator">
    <a type="button" class="statue_button btn btn-primary model-choice_previous" id="statue_model-choice_previous"><%= t "previous" %></a>
  </div>

  
</section>







<section class="questions">
  <h1><%= t "finalQuestions" %></h1>

  <div class="row model_question_screen1" id="statue_question_screen1"><div class="span2"></div>
    <div class="span9" id="statue_questions_div">
      <%= form_tag(answers_path, remote: true) do %>
      <%= hidden_field_tag(:model, nil, id:"statue_model_field", class:"question_model_field") %>
      <%= hidden_field_tag(:question1, nil, id:"statue_question1_field", class:"question_question1_field") %>
      <%= label_tag(:answer1, nil, id:"statue_question1_label", class:"question_question1_label") %>
      <%= text_area_tag(:answer1, nil, id:"statue_answer1_field", class:"question_answer1_field") %>
      <%= hidden_field_tag(:question2, nil, id:"statue_question2_field", class:"question_question2_field") %>
      <%= label_tag(:answer2, nil, id:"statue_question2_label", class:"question_question2_label") %>
      <%= text_area_tag(:answer2, nil, id:"statue_answer2_field", class:"question_answer2_field") %>
      <%= hidden_field_tag(:question3, nil, id:"statue_question3_field", class:"question_question3_field") %>
      <%= hidden_field_tag(:answer3, nil, id:"statue_answer3_field", class:"question_answer3_field") %>
      <%= hidden_field_tag(:question4, nil, id:"statue_question4_field", class:"question_question4_field") %>
      <%= label_tag(:answer4, nil, id:"statue_question4_label", class:"question_question4_label") %>
      <%= text_area_tag(:answer4, nil, id:"statue_answer4_field", class:"question_answer4_field") %>
      
      <%= hidden_field_tag(:param_k, nil, id:"statue_param_k", class: "question_param_k" ) %>
      <%= hidden_field_tag(:param_h, nil, id:"statue_param_h", class: "question_param_h" ) %>
      <%= hidden_field_tag(:param_b, nil, id:"statue_param_b", class: "question_param_b" ) %>
      
      <br />
      <%= submit_tag(:save, value:"Submeter", confirm:"Deseja introduzir estas respostas?", class:"btn btn-success questions_confirm_answers_button", style:"float: left") %>
      <% end %>
    </div>
    <div class="span3"></div>
  </div>

  <div class="row model_question_screen2" id="statue_question_screen2"><div class="span2"></div>
    <div class="span9" id="statue_questions_after_div">
      <%= t "endActivityMessage" %>
    </div>
    
  </div>

  

  <div class="btn-group statue_navigator">
    <a type="button" class="statue_button btn btn-primary model_questions_previous" id="statue_questions_previous" style:"margin:20px 30px 0 0"><%= t "previous" %></a>
  </div>
</section>



</div>