config/routes.rb
Plotomeu::Application.routes.draw do
  devise_for :users

  resources :teachers
  resources :students

  resources :thermal_capacities 
  resources :thermal_capacities_materials
  resources :thermal_capacities_temp
  resources :thermo_filter do
    member do
      get "filter"
    end
  end

  resources :pendulum_length
  resources :pendulum_mass
  resources :pendulum_angle
  resources :pendulum_filter do
    member do 
      get "filter"
    end
  end

  resources :static_pages do
    collection do
      get "set_name"
      get "filter"
    end
  end
  resources :data_points do
    collection do
      get "updateGraph"
    end
  end

  resources :answers do
    collection do
      post "leave_page"
    end
  end

  resources :templates 

  resources :activities do
    member do
      get "updateTeacherGraph"
      get "switch"
    end
  end

  resources :statues do
    collection do
      post "add_prediction"
    end
  end

  root to: "static_pages#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :code, :deadline,  :description
  
  validates :code, presence: true, uniqueness: {scope: :template_id}, length: {minimum: 3}
  validates :template_id, presence: true
  validates :user_id, presence: true
  
  
  belongs_to :template
  has_many :data_points, dependent: :destroy
  has_many :answers, dependent: :destroy
  
  has_many :filtered, class_name: "Activity", foreign_key: "filter_id"
  belongs_to :filter, class_name: "Activity"


  def filter?
    self.filtered.count > 0 ? true : false
  end
end

app/models/answer.rb
# -*- coding: utf-8 -*-

class Answer < ActiveRecord::Base
  attr_accessible  :answers, :questions,  :time_submission, :submited, :parameters

  validates :activity_id, presence: true
  validates :user_id, presence: true
  validates :answers, presence: true
  validates :questions, presence: true
  validates :parameters, presence: true
  validate :answers_length

  serialize :answers
  serialize :questions
  serialize :parameters

  belongs_to :user
  has_many :data_points, dependent: :destroy
  
  def answers_length
    if answers && questions 
      if answers.length != questions.length
        errors.add(:answers, "o número de respostas não é igual ao número de perguntas")
      end
    end
  end

  scope :old, -> { where("created_at < ? and submited = ?", Time.now-18000, false)}
  scope :submited, -> { where("submited = ?", true) }

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title

  has_many :sub_categories, dependent: :destroy
end

app/models/data_point.rb
class DataPoint < ActiveRecord::Base
  attr_accessible :x, :y, :series

  validates :x, presence: true
  validates :y, presence: true
  validates :answer_id, presence: true
  validates :activity_id, presence: true

  belongs_to :answer
  belongs_to :activity
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  
  attr_accessible  :title

  belongs_to :category
end

app/models/template.rb
class Template < ActiveRecord::Base
  attr_accessible :url, :description, :title

  validates :url, presence: true, uniqueness: {case_sensitive: false}
  validates :description, presence: true
  validates :title, presence: true, uniqueness: {case_sensitive: false}


  has_many :activities, dependent: :destroy

  has_many :filtered, class_name: "Template", foreign_key: "filter_id"
  belongs_to :filter, class_name: "Template"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :login, :name, :role , :account_type
  # attr_accessible :title, :body

  
  validates :login, presence: true, uniqueness: {case_sensitive: false}
  validates :role, presence: true
  validate :student_name
  
  has_many :activities
  has_many :data_points, through: :answers
  has_many :answers, dependent: :destroy
  serialize :completed

  before_validation :populate_fields

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def populate_fields
    x = rand(36**7...36**8).to_s(36)
    z = rand(36**7...36**8).to_s(36)
    if self.role == "1" || self.role == "student" then self.role = "student" else self.role = "teacher" end
    
    self.email = "#{z}noEmail#{x}@example.com" if !self.email || self.email == ""
    self.login = "#{z}noLogin#{x}" if self.account_type == 2
    self.completed ||= []
  end


  def student_name
    if self.role == "student"
      if !self.name || self.name == ""
        errors.add(:name, "no_name_error")
      end
    end
  end


  def get_activity_with_template(id)
    self.activities.includes(:template).where(id: id).first
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include AnswerCompilation

  before_filter :authenticate_user!, only: [:destroy]

  def create
    a = Answer.find(session[:answer])
    a.questions = []
    a.answers = []
    a.parameters = []

    a.questions << "modelo"
    a.answers << params[:model]
    
    a.questions << params[:question1]
    a.questions << params[:question2]
    a.questions << params[:question3]
    a.questions << params[:question4]
    
    a.answers << params[:answer1]
    a.answers << params[:answer2]
    a.answers << params[:answer3]
    a.answers << params[:answer4]

    a.parameters << params[:param_k]
    a.parameters << params[:param_h]
    a.parameters << params[:param_b]
    
    a.time_submission = Time.now
    
    a.submited = true
    a.save

    markAnswerCompleted(session[:activity]) if signed_in?
    
    session[:activity] = nil

    respond_to do |format| 
      format.js {render "#{session[:url]}/create_answers" }
    end
    
  end



  def destroy
    a = Answer.find(params[:id])
    @activity = current_user.activities.where(id: params[:activity_id]).first
    @answers = @activity.answers.includes(:data_points, :user).order("users.name")
    if @activity && a.activity_id == @activity.id
      u = User.find(a.user_id)
      u.completed.delete(@activity.template_id)
      u.save
      a.destroy
    else
      redirect_to root_path
    end

    compile_answers()
      

    respond_to do |format|
      format.js 
    end
  end

  
  def leave_page
    if (session[:answer])
      a = Answer.find(session[:answer])
      unless a.submited
        a.destroy
      end
    end

    respond_to do |format|
      format.js
    end
  end


  private
  def markAnswerCompleted(a)
    act = Activity.find(a)
    t = act.template_id
    current_user.completed << t unless current_user.completed.include? t
    current_user.save
  end
end

app/controllers/statues_controller.rb
class StatuesController < ApplicationController

  def index
    if session[:url] != request.path || session[:activity] == nil
      redirect_to root_path
    end
    
    @user = user_signed_in?
  end


  def add_prediction
    session[:prediction] = params[:mass]

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_cache_buster

  def show
    if current_user.id == params[:id].to_i
      act = current_user.activities.includes(:answers).order(:id)
      @activities = []

      act.each do |i|
        @activities << i unless i.filter?
      end
    else
      redirect_to root_path
    end
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_points_helper.rb
module DataPointsHelper
end

app/helpers/pendulum_angle_helper.rb
module PendulumAngleHelper
end

app/helpers/pendulum_filter_helper.rb
module PendulumFilterHelper
end

app/helpers/pendulum_mass_helper.rb
module PendulumMassHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statues_helper.rb
module StatuesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/thermo_filter_helper.rb
module ThermoFilterHelper
end

app/views/teachers/_teacher_activities.html.erb
<% @activities.each do |a| %>
    <div class="ptolemy_teacher_board_cell">
      <div>
	 <b><%= link_to a.template.title, a, data:{activity: a.id} %></b><% if a.description != "" %> - <%= a.description %> <% end %>
	 <% if a.filter_id %>
	 - <% if a.inactive %><%= link_to "activar", switch_activity_path(a.id), remote: true %><% else %><%= link_to "desactivar", switch_activity_path(a.id), remote: true %><% end %>
	 <% end %>
      </div>
      <div>
	 código: <%= a.code %><% if a.deadline %> - limite: <%= a.deadline.strftime("%d-%m-%Y") %> <% end %> - respostas: <%= a.answers.submited.count %>
      </div>
    </div>
    <% end %>

app/views/teachers/remove_data_points.js.erb
$('#ptolemy_dashboard').html("<%= escape_javascript(render(:partial => 'activities/dashboard')) %>");







var updateGraph = function(points, url) {
	$.ajax(url,{
	    	
	    method: "get",
	    data: {points: points},
	    success: function(json) {
		var formatted_data = [];
		
		for (var k in json) {
		    if (k != "names" && k != "process") {
			if (json["process"] === 1) {
			    formatted_data.push({data: json[k],
						 points: {show:true},
						 label: json["names"][k],
						 color: $("label[for='"+k+"']").data("color"),
						});
			}
			else if (json["process"] === 2) {
			    formatted_data.push({data: json[k],
						 points: {show:true},
						 label: k,
						});
			}
		    }	
		    	    
		}

		$("#teacher_graph_div").html("");
		var plot = $.plot($("#teacher_graph_div"),
		      formatted_data, {
               
			  grid: { hoverable: true, clickable: true },
			  xaxis: { min: 0,  },
			  yaxis: { min: 0,  },
			  legend: {show: false},
		      });
		
		$(".flot-x-axis").css({left: "10px"});
		
		function showTooltip(x, y, contents) {
		    $('<div id="tooltip">' + contents + '</div>').css( {
			position: 'absolute',
			display: 'none',
			top: y + 5,
			left: x + 5,
			border: '1px solid #fdd',
			padding: '2px',
			'background-color': '#fee',
			opacity: 0.80
		    }).appendTo("body").fadeIn(200);
		}

		var previousPoint = null;
		$("#teacher_graph_div").bind("plothover", function (event, pos, item) {
        
		    if (item && json.process === 1) {
			if (previousPoint != item.dataIndex) {
			    previousPoint = item.dataIndex;
                    
			    $("#tooltip").remove();
			    var x = item.datapoint[0].toFixed(2),
                        y = item.datapoint[1].toFixed(2);
			    
			    showTooltip(item.pageX, item.pageY,
					item.series.label);
			}
		    }
		    else if (item && json.process === 2) {
			if (previousPoint != item.dataIndex) {
			    previousPoint = item.dataIndex;
			    
			    $("#tooltip").remove();
			    var x = item.datapoint[0].toFixed(2),
                            y = item.datapoint[1].toFixed(2);
			    var i = json.meta[item.seriesIndex][item.dataIndex];

			    showTooltip(item.pageX, item.pageY,
					$("label[for='"+i+"']").text());
			}
		    }

		    else {
			$("#tooltip").remove();
			previousPoint = null;            
		    }
        
		});

		$("#teacher_graph_div").on("plotclick", function (event, pos, item) {
		    if (item && json.process === 1) {
			$("#activity_point_info").html("<p>"+item.series.label+"<p/><p>x: "+item.datapoint[0]+"</p><p>y: "+item.datapoint[1]+"</p>");
			
		    }
		    else if (item && json.process === 2){
		        var i = json.meta[item.seriesIndex][item.dataIndex];
			var t = $("label[for='"+i+"']").text();
			$("#activity_point_info").html("<p>"+t+"</p><p>"+item.series.label+"<p/><p>x: "+item.datapoint[0]+"</p><p>y: "+item.datapoint[1]+"</p>");
		    }
		});


	    },
	    
	}); 
    }	


var path = window.location.pathname;
path = path.split("/");
  


var activity = parseInt(path[2]);

var url = "/activities/"+activity+"/updateTeacherGraph";
var points = [];		
	
$(".userbox>:checked").each(function()	{
    var box = $(this);			
    points.push(parseInt(box.attr("name")));
    
}); 

updateGraph(points, url);	

app/views/teachers/show.html.erb
<%= render "layouts/navbar" %>


<div class="row">
  <div id="ptolemy_teacher_board" class="span8">
    <%= render "teacher_activities" %>
  </div>
</div>