config/routes.rb
Plotomeu::Application.routes.draw do
  devise_for :users

  resources :teachers
  resources :students

  resources :thermal_capacities 
  resources :thermal_capacities_materials
  resources :thermal_capacities_temp
  resources :thermo_filter do
    member do
      get "filter"
    end
  end

  resources :pendulum_length
  resources :pendulum_mass
  resources :pendulum_angle
  resources :pendulum_filter do
    member do 
      get "filter"
    end
  end

  resources :static_pages do
    collection do
      get "set_name"
      get "filter"
    end
  end
  resources :data_points do
    collection do
      get "updateGraph"
    end
  end

  resources :answers do
    collection do
      post "leave_page"
    end
  end

  resources :templates 

  resources :activities do
    member do
      get "updateTeacherGraph"
      get "switch"
    end
  end

  resources :statues do
    collection do
      post "add_prediction"
    end
  end

  root to: "static_pages#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :code, :deadline,  :description
  
  validates :code, presence: true, uniqueness: {scope: :template_id}, length: {minimum: 3}
  validates :template_id, presence: true
  validates :user_id, presence: true
  
  
  belongs_to :template
  has_many :data_points, dependent: :destroy
  has_many :answers, dependent: :destroy
  
  has_many :filtered, class_name: "Activity", foreign_key: "filter_id"
  belongs_to :filter, class_name: "Activity"


  def filter?
    self.filtered.count > 0 ? true : false
  end
end

app/controllers/activities_controller.rb
# -*- coding: utf-8 -*-
class ActivitiesController < ApplicationController
  include AnswerCompilation

  before_filter :authenticate_user!
  before_filter :set_cache_buster, only: [:show]

  def create
    template = params[:activity].delete(:template_id)
    a = current_user.activities.build(params[:activity])
    a.template_id = template
    a.save

    t = Template.find(template)
    
    createFilteredActivities(t, params, a)
    
    redirect_to templates_path
    
  end


  def show
    @activity = current_user.get_activity_with_template(params[:id])
    
    @user_ids = get_users_selected_in_checkboxes(params)
    

    if @activity
      compile_answers()
      @answers = @activity.answers.includes(:user).order("users.name")
      
    else
      flash[:alert] = "Não pode aceder a essa atividade" 
      redirect_to root_path
    end

    respond_to do |format|
      format.html
      format.js
    end
    
  end




  def updateTeacherGraph
    d = getDataForTeacher(params[:id], params[:points])
  
    respond_to do |format|
      format.json {render json: d.to_json}
    end
  end




  def switch
    a = Activity.find(params[:id])
    a.inactive = !a.inactive
    a.save
    
    @activities = getNonFilteringActivities
    
    
    respond_to do |format|
      format.js
    end
  end





  private
  def getDataForTeacher(activity, points)
    activity = Activity.find(activity)
    if activity
      answers = activity.answers.includes(:user,:data_points).where("id in (?)", points)
      
      names = {}
      d = {}
      params = {}
      max_x = 0

      if answers.any? && !answers.first.data_points.first.series 
        answers.each do |a|
          a.data_points.each do |i|
            max_x = i.x if i.x > max_x
          end
        end
        max_x*=1.1

        d[:process] = 1
        answers.each do |a|
          a.data_points.each do |i|
            if d[a.id]
              d[a.id] << [i.x,i.y]
            else
              names[a.id] = a.user.name
              d[a.id] = [[i.x,i.y]]
            end
          end
          
          params[a.id] = getModelPoints(a.answers[0], a.parameters, max_x)
        end
        d[:names] = names
        d[:params] = params

      elsif answers.any?
        answers_id = []
        answers.each do |a|
          answers_id << a.id
        end
        d[:process] = 2
        meta = {}
        series = activity.data_points.select(:series).group(:series)
        series.each_with_index do |i,index|
          points = activity.data_points.where("series = ?", i.series)
          d[i.series] = []
          meta[index] = []
          points.each do |j|
            if answers_id.include? j.answer_id 
              d[i.series] << [j.x,j.y] 
              meta[index] << j.answer_id
            end
          end
        end
        
        d[:meta] = meta
      end
    end
    
    d
  end



  def getModelPoints(model, params, max) 
    points = []
    step = max/40
    counter = 0
    model = model.to_i

    tmp = []
    params.each do |p|
      tmp << p.to_f
    end
    
    40.times do |i|
      if model == 1
        points << [counter, tmp[0]*counter+tmp[2]]
      elsif model == 2
        points << [counter, tmp[0]*(counter-tmp[1])**2+tmp[2]]
      elsif model == 3
        points << [counter, tmp[0]*(counter-tmp[1])**3+tmp[2]]
      elsif model == 4
        points << [counter, tmp[0]*(counter-tmp[1])**(0.5)+tmp[2]]
      elsif model == 5
        points << [counter, tmp[2]]
      end
      counter += step
    end
      
    return points
  end




    
  def get_users_selected_in_checkboxes(params)
    user_ids = []
    params.each do |i|
      user_ids << i[7,9] if i[0,7] == "userbox"
    end
    user_ids
  end

  def getNonFilteringActivities
    act = current_user.activities.includes(:answers).order(:id)
    @activities = []

    act.each do |i|
      @activities << i unless i.filter?
    end
  end

  
  def createFilteredActivities(t, params, a)
    if t.filtered.count > 0 
      t.filtered.each do |i|
        x = current_user.activities.build(params[:activity])
        x.template_id = i.id
        x.filter_id = a.id
        x.inactive = true unless params[("filter"+i.id.to_s).to_sym]
        x.save
      end
    end
  end


end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_dashboard.html.erb
<h2><% @activity.template.title %></h2>
    
   
    <% @students.each do |s| %>
    <div class="ptolemy_dashboard_cell">
      <div class="ptolemy_student_dashboard_header">
	 <span class="ptolemy_student_name"><%= s[:name] %></span>
	 <span class="ptolemy_student_model"><%= t "model" %>: <%= t(s[:answers][0][1]) %></span>   
	 <span class="ptolemy_student_measurements">medições: <%= s[:count] %></span>
	 <span class="ptolemy_student_time">  <%= pluralize(((s[:end]-s[:start])/60).round, "minuto") %></span>
	 <span><%= link_to "remover", answer_path(s[:answer], activity_id:@activity.id), method: :delete, confirm: "Esta ação vai remover todo o trabalho do(a) estudante #{s[:name]}. Continuar?", remote:true, class:"student_removal" %></span>
      </div>
      
      <div class="ptolemy_student_dashboard_body">
	<div class="ptolemy_student_dashboard_points">
	  <h4> Pontos Recolhidos </h4>
	  <table id="points_student_<%= s[:id] %>">
	    <tr><th>x</th><th>y</th></tr>
	    <% s[:points].all.each do |p| %>
	    <tr id="point_<%= p.id %>"><td><%= p.x %></td><td><%= p.y %></td><td><% if p.series %><%= t(p.series) %><% end %></td><td><%= link_to "remover", p, method: :delete, confirm: "Remover este ponto?", remote: true %></tr>
	    <% end %>
	  </table>
	</div>
 
	<% s[:answers].each_with_index do |a,i| %>
	 <% if i != 0 %>
	 <% if a[1] != "" %>
	 <p class="ptolemy_student_question"><%= raw(a[0]) %></p>
	 <p class="ptolemy_student_answer"><%= a[1] %></p>
	 <br />
	 <% end %>
	 <% end %>
	 <% end %>
      </div>
    </div>
    <% end %>

app/views/activities/_graph_dat.html.erb
<%= form_tag("#", id:"teacher_graph_data_form") do %>
    <div class="data_type">
      <%= check_box_tag("points", 1, checked:true) %>
      <%= label_tag "points", t("points"), class:"checkbox inline", } %>
    </div>
    <div class="data_type">
      <%= check_box_tag("model", 1, checked:true) %>
      <%= label_tag "model", t("model"), class:"checkbox inline", } %>
    </div>
    
    <% end %>

app/views/activities/_graph_data.html.erb
<%= form_tag("#", id:"teacher_graph_data_form") do %>
  <div class="data_type">
    <%= check_box_tag("points_box", 1, checked:true) %>
    <%= label_tag "points_box", t("points"), class:"checkbox inline" %>
  </div>
  <div class="data_type">
    <%= check_box_tag("models_box", 0) %>
    <%= label_tag "models_box", t("models"), class:"checkbox inline" %>
  </div>
<% end %>
    

app/views/activities/_graph_names.html.erb
<%= form_tag("#", id:"teacher_graph_form") do %>
    <% @answers.each_with_index do |a,index| %>
    <div class="userbox">
      <%= check_box_tag(a.id, 1, checked:true) %>
      <%= label_tag a.id, a.user.name, class:"checkbox inline", data:{color:index} %>
    </div>
    <% end %>
    
    <% end %>

app/views/activities/show.html.erb
<%= render "layouts/navbar" %>

<div class="row">
  <div class="span3" id="teacher_graph_data">
    <%= render "graph_data" %>
  </div>
  <div class="span3" id="teacher_graph_names">
    <%= render "graph_names" %>
  </div>
  <div class="span6">
    <div class="graph_div" id="teacher_graph_div"></div>
  </div>
  <div class="span3">
    <div id="activity_point_info"></div>
  </div>
</div>
<div class="row">
  <div class="span10" id="ptolemy_dashboard">
    <%= render "dashboard" %>
  
  </div>
  
  <div class="span3" >
    <%= link_to "voltar", teacher_path(current_user.id) %>
  </div>
</div>

app/views/activities/switch.js.erb
$('#ptolemy_teacher_board').html("<%= escape_javascript(render(:partial => 'teachers/teacher_activities')) %>");